export enum FormIds {
	Renome = "LCST::Form/Renome",
	Anotar = "LCST::Form/Anotar",
	Advertir = "LCST::Form/Advertir",
	Sugestão = "LCST::Form/Sugestão",
	Avaliação = "LCST::Form/Avaliação",
	Entrevista = "LCST::Form/Entrevista",
	Reclamação = "LCST::Form/Reclamação",
	Acompanhamento = "LCST::Form/Acompanhamento",
	AcompanhamentoAdm = "LCST::Form/AcompanhamentoAdm",
	Organizacional = "LCST::Form/Organizacional",
	OrganizacionalCorrecao = "LCST::Form/OrganizacionalCorrecao",
	Elogio = "LCST::Form/Elogio",
	criarMedalha = "LCST::Form/criarMedalha",
	deletarMedalha = "LCST::Form/deletarMedalha",
	listarMedalhas = "LCST::Form/listarMedalhas",
	editarMedalha = "LCST::Form/editarMedalha",
	trocarHabboConta = "LCST::Form/trocarHabboConta",
	trocarDiscordConta = "LCST::Form/trocarDiscordConta",
}
